title: Ketan Yeola
email: ketanyeola321@gmail.com
description: >
  Game Developer Portfolio
url: "https://ketanyeola.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Ketan Yeola"
  bio: "Game Developer | Unreal | XR | Virtual Production "
  avatar: "/assets/images/avatar.jpg"

minimal_mistakes_skin: "dark"

collections:
  projects:
    output: true
    permalink: /projects/:name/
