title: Ketan Yeola
description: Game Developer Portfolio
url: "https://ketanyeola.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: dark

author:
  name: "Ketan Yeola"
  bio: "Game Developer | Gameplay & Systems"
  avatar: "/assets/images/placeholder.jpg"

collections:
  projects:
    output: true
